/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.auth.model;

import com.alterian.auth.model.Applications;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthenticationResults
 */
public class AuthenticationResultsTest {
    private final AuthenticationResults model = new AuthenticationResults();

    /**
     * Model tests for AuthenticationResults
     */
    @Test
    public void testAuthenticationResults() {
        // TODO: test AuthenticationResults
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'loginID'
     */
    @Test
    public void loginIDTest() {
        // TODO: test loginID
    }

    /**
     * Test the property 'sites'
     */
    @Test
    public void sitesTest() {
        // TODO: test sites
    }

    /**
     * Test the property 'passwordExpired'
     */
    @Test
    public void passwordExpiredTest() {
        // TODO: test passwordExpired
    }

}
