/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.auth.model;

import com.alterian.auth.model.APICursor;
import com.alterian.auth.model.APIMetadataType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAPIMetadataRequest
 */
public class GetAPIMetadataRequestTest {
    private final GetAPIMetadataRequest model = new GetAPIMetadataRequest();

    /**
     * Model tests for GetAPIMetadataRequest
     */
    @Test
    public void testGetAPIMetadataRequest() {
        // TODO: test GetAPIMetadataRequest
    }

    /**
     * Test the property 'cursor'
     */
    @Test
    public void cursorTest() {
        // TODO: test cursor
    }

    /**
     * Test the property 'includeEmpty'
     */
    @Test
    public void includeEmptyTest() {
        // TODO: test includeEmpty
    }

    /**
     * Test the property 'metadataName'
     */
    @Test
    public void metadataNameTest() {
        // TODO: test metadataName
    }

    /**
     * Test the property 'metadataType'
     */
    @Test
    public void metadataTypeTest() {
        // TODO: test metadataType
    }

}
