/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.auth.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetIdentityUrlRequest
 */
public class GetIdentityUrlRequestTest {
    private final GetIdentityUrlRequest model = new GetIdentityUrlRequest();

    /**
     * Model tests for GetIdentityUrlRequest
     */
    @Test
    public void testGetIdentityUrlRequest() {
        // TODO: test GetIdentityUrlRequest
    }

    /**
     * Test the property 'identityId'
     */
    @Test
    public void identityIdTest() {
        // TODO: test identityId
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

}
