/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.auth.model;

import com.alterian.auth.model.APICursor;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetSettingsValuesRequest
 */
public class GetSettingsValuesRequestTest {
    private final GetSettingsValuesRequest model = new GetSettingsValuesRequest();

    /**
     * Model tests for GetSettingsValuesRequest
     */
    @Test
    public void testGetSettingsValuesRequest() {
        // TODO: test GetSettingsValuesRequest
    }

    /**
     * Test the property 'cursor'
     */
    @Test
    public void cursorTest() {
        // TODO: test cursor
    }

    /**
     * Test the property 'issuerId'
     */
    @Test
    public void issuerIdTest() {
        // TODO: test issuerId
    }

    /**
     * Test the property 'loginId'
     */
    @Test
    public void loginIdTest() {
        // TODO: test loginId
    }

    /**
     * Test the property 'settingIds'
     */
    @Test
    public void settingIdsTest() {
        // TODO: test settingIds
    }

    /**
     * Test the property 'siteId'
     */
    @Test
    public void siteIdTest() {
        // TODO: test siteId
    }

}
