/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.auth.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An enum which can be used to filter down the request to a particular type. If this is not specified then all are returned
 */
@JsonAdapter(APIMetadataType.Adapter.class)
public enum APIMetadataType {
  
  /**
   * Show only method calls and the rules for the parameters in the method
   */
  METHOD(1),
  
  /**
   * Show only class types, and the rules for the properties in the class
   */
  CLASS(2),
  
  NUMBER_unknown_default_open_api(11184809);

  private Integer value;

  APIMetadataType(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static APIMetadataType fromValue(Integer value) {
    for (APIMetadataType b : APIMetadataType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return NUMBER_unknown_default_open_api;
  }

  public static class Adapter extends TypeAdapter<APIMetadataType> {
    @Override
    public void write(final JsonWriter jsonWriter, final APIMetadataType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public APIMetadataType read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return APIMetadataType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    Integer value = jsonElement.getAsInt();
    APIMetadataType.fromValue(value);
  }
}

