/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.auth.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.auth.JSON;

/**
 * SAMLAuthenticationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class SAMLAuthenticationRequest {
  public static final String SERIALIZED_NAME_SA_M_L_RESPONSE = "SAMLResponse";
  @SerializedName(SERIALIZED_NAME_SA_M_L_RESPONSE)
  private String saMLResponse;

  public SAMLAuthenticationRequest() {
  }

  public SAMLAuthenticationRequest saMLResponse(String saMLResponse) {
    this.saMLResponse = saMLResponse;
    return this;
  }

   /**
   * Properly signed and formatted SAMLResponse.
   * @return saMLResponse
  **/
  @javax.annotation.Nullable
  public String getSaMLResponse() {
    return saMLResponse;
  }

  public void setSaMLResponse(String saMLResponse) {
    this.saMLResponse = saMLResponse;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SAMLAuthenticationRequest saMLAuthenticationRequest = (SAMLAuthenticationRequest) o;
    return Objects.equals(this.saMLResponse, saMLAuthenticationRequest.saMLResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saMLResponse);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SAMLAuthenticationRequest {\n");
    sb.append("    saMLResponse: ").append(toIndentedString(saMLResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("SAMLResponse");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SAMLAuthenticationRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SAMLAuthenticationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SAMLAuthenticationRequest is not found in the empty JSON string", SAMLAuthenticationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SAMLAuthenticationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SAMLAuthenticationRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("SAMLResponse") != null && !jsonObj.get("SAMLResponse").isJsonNull()) && !jsonObj.get("SAMLResponse").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `SAMLResponse` to be a primitive type in the JSON string but got `%s`", jsonObj.get("SAMLResponse").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SAMLAuthenticationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SAMLAuthenticationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SAMLAuthenticationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SAMLAuthenticationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SAMLAuthenticationRequest>() {
           @Override
           public void write(JsonWriter out, SAMLAuthenticationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SAMLAuthenticationRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SAMLAuthenticationRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SAMLAuthenticationRequest
  * @throws IOException if the JSON string is invalid with respect to SAMLAuthenticationRequest
  */
  public static SAMLAuthenticationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SAMLAuthenticationRequest.class);
  }

 /**
  * Convert an instance of SAMLAuthenticationRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

