/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.auth.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.auth.JSON;

/**
 * SetEMServiceURLRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class SetEMServiceURLRequest {
  public static final String SERIALIZED_NAME_EM_SERVICE_U_R_L = "EMServiceURL";
  @SerializedName(SERIALIZED_NAME_EM_SERVICE_U_R_L)
  private String emServiceURL;

  public SetEMServiceURLRequest() {
  }

  public SetEMServiceURLRequest emServiceURL(String emServiceURL) {
    this.emServiceURL = emServiceURL;
    return this;
  }

   /**
   * New EM service URL
   * @return emServiceURL
  **/
  @javax.annotation.Nullable
  public String getEmServiceURL() {
    return emServiceURL;
  }

  public void setEmServiceURL(String emServiceURL) {
    this.emServiceURL = emServiceURL;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetEMServiceURLRequest setEMServiceURLRequest = (SetEMServiceURLRequest) o;
    return Objects.equals(this.emServiceURL, setEMServiceURLRequest.emServiceURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emServiceURL);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetEMServiceURLRequest {\n");
    sb.append("    emServiceURL: ").append(toIndentedString(emServiceURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("EMServiceURL");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SetEMServiceURLRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SetEMServiceURLRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SetEMServiceURLRequest is not found in the empty JSON string", SetEMServiceURLRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SetEMServiceURLRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SetEMServiceURLRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("EMServiceURL") != null && !jsonObj.get("EMServiceURL").isJsonNull()) && !jsonObj.get("EMServiceURL").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `EMServiceURL` to be a primitive type in the JSON string but got `%s`", jsonObj.get("EMServiceURL").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SetEMServiceURLRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SetEMServiceURLRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SetEMServiceURLRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SetEMServiceURLRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SetEMServiceURLRequest>() {
           @Override
           public void write(JsonWriter out, SetEMServiceURLRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SetEMServiceURLRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SetEMServiceURLRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SetEMServiceURLRequest
  * @throws IOException if the JSON string is invalid with respect to SetEMServiceURLRequest
  */
  public static SetEMServiceURLRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SetEMServiceURLRequest.class);
  }

 /**
  * Convert an instance of SetEMServiceURLRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

