/*
 * Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.auth.api;

import com.alterian.auth.ApiCallback;
import com.alterian.auth.ApiClient;
import com.alterian.auth.ApiException;
import com.alterian.auth.ApiResponse;
import com.alterian.auth.Configuration;
import com.alterian.auth.Pair;
import com.alterian.auth.ProgressRequestBody;
import com.alterian.auth.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.alterian.auth.model.AddLoginDefaultResponse;
import com.alterian.auth.model.AddLoginRequest;
import com.alterian.auth.model.DisableLoginRequest;
import com.alterian.auth.model.EnableLoginRequest;
import com.alterian.auth.model.GetCurrentLoginDefaultResponse;
import com.alterian.auth.model.GetLoginRequest;
import com.alterian.auth.model.GetLoginsDefaultResponse;
import com.alterian.auth.model.GetLoginsRequest;
import com.alterian.auth.model.LogoutDefaultResponse;
import com.alterian.auth.model.RenameLoginRequest;
import com.alterian.auth.model.UpdateLoginExRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LoginsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LoginsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LoginsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addLogin
     * @param addLoginRequest Add a login into the system (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addLoginCall(AddLoginRequest addLoginRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = addLoginRequest;

        // create path and map variables
        String localVarPath = "/AddLogin";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "TokenAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addLoginValidateBeforeCall(AddLoginRequest addLoginRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'addLoginRequest' is set
        if (addLoginRequest == null) {
            throw new ApiException("Missing the required parameter 'addLoginRequest' when calling addLogin(Async)");
        }

        return addLoginCall(addLoginRequest, _callback);

    }

    /**
     * Add a login into the system
     * Add a login into the system
     * @param addLoginRequest Add a login into the system (required)
     * @return AddLoginDefaultResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public AddLoginDefaultResponse addLogin(AddLoginRequest addLoginRequest) throws ApiException {
        ApiResponse<AddLoginDefaultResponse> localVarResp = addLoginWithHttpInfo(addLoginRequest);
        return localVarResp.getData();
    }

    /**
     * Add a login into the system
     * Add a login into the system
     * @param addLoginRequest Add a login into the system (required)
     * @return ApiResponse&lt;AddLoginDefaultResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AddLoginDefaultResponse> addLoginWithHttpInfo(AddLoginRequest addLoginRequest) throws ApiException {
        okhttp3.Call localVarCall = addLoginValidateBeforeCall(addLoginRequest, null);
        Type localVarReturnType = new TypeToken<AddLoginDefaultResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add a login into the system (asynchronously)
     * Add a login into the system
     * @param addLoginRequest Add a login into the system (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addLoginAsync(AddLoginRequest addLoginRequest, final ApiCallback<AddLoginDefaultResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = addLoginValidateBeforeCall(addLoginRequest, _callback);
        Type localVarReturnType = new TypeToken<AddLoginDefaultResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for disableLogin
     * @param disableLoginRequest Flag a login as disabled (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call disableLoginCall(DisableLoginRequest disableLoginRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = disableLoginRequest;

        // create path and map variables
        String localVarPath = "/DisableLogin";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "TokenAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call disableLoginValidateBeforeCall(DisableLoginRequest disableLoginRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'disableLoginRequest' is set
        if (disableLoginRequest == null) {
            throw new ApiException("Missing the required parameter 'disableLoginRequest' when calling disableLogin(Async)");
        }

        return disableLoginCall(disableLoginRequest, _callback);

    }

    /**
     * Flag a login as disabled
     * Flag a login as disabled
     * @param disableLoginRequest Flag a login as disabled (required)
     * @return LogoutDefaultResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public LogoutDefaultResponse disableLogin(DisableLoginRequest disableLoginRequest) throws ApiException {
        ApiResponse<LogoutDefaultResponse> localVarResp = disableLoginWithHttpInfo(disableLoginRequest);
        return localVarResp.getData();
    }

    /**
     * Flag a login as disabled
     * Flag a login as disabled
     * @param disableLoginRequest Flag a login as disabled (required)
     * @return ApiResponse&lt;LogoutDefaultResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LogoutDefaultResponse> disableLoginWithHttpInfo(DisableLoginRequest disableLoginRequest) throws ApiException {
        okhttp3.Call localVarCall = disableLoginValidateBeforeCall(disableLoginRequest, null);
        Type localVarReturnType = new TypeToken<LogoutDefaultResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Flag a login as disabled (asynchronously)
     * Flag a login as disabled
     * @param disableLoginRequest Flag a login as disabled (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call disableLoginAsync(DisableLoginRequest disableLoginRequest, final ApiCallback<LogoutDefaultResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = disableLoginValidateBeforeCall(disableLoginRequest, _callback);
        Type localVarReturnType = new TypeToken<LogoutDefaultResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for enableLogin
     * @param enableLoginRequest Flag a login as enabled.  If a login has been expired due to inactivity, this will enable it to be logged into again (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call enableLoginCall(EnableLoginRequest enableLoginRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = enableLoginRequest;

        // create path and map variables
        String localVarPath = "/EnableLogin";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "TokenAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call enableLoginValidateBeforeCall(EnableLoginRequest enableLoginRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'enableLoginRequest' is set
        if (enableLoginRequest == null) {
            throw new ApiException("Missing the required parameter 'enableLoginRequest' when calling enableLogin(Async)");
        }

        return enableLoginCall(enableLoginRequest, _callback);

    }

    /**
     * Flag a login as enabled.  If a login has been expired due to inactivity, this will enable it to be logged into again
     * Flag a login as enabled.  If a login has been expired due to inactivity, this will enable it to be logged into again
     * @param enableLoginRequest Flag a login as enabled.  If a login has been expired due to inactivity, this will enable it to be logged into again (required)
     * @return LogoutDefaultResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public LogoutDefaultResponse enableLogin(EnableLoginRequest enableLoginRequest) throws ApiException {
        ApiResponse<LogoutDefaultResponse> localVarResp = enableLoginWithHttpInfo(enableLoginRequest);
        return localVarResp.getData();
    }

    /**
     * Flag a login as enabled.  If a login has been expired due to inactivity, this will enable it to be logged into again
     * Flag a login as enabled.  If a login has been expired due to inactivity, this will enable it to be logged into again
     * @param enableLoginRequest Flag a login as enabled.  If a login has been expired due to inactivity, this will enable it to be logged into again (required)
     * @return ApiResponse&lt;LogoutDefaultResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LogoutDefaultResponse> enableLoginWithHttpInfo(EnableLoginRequest enableLoginRequest) throws ApiException {
        okhttp3.Call localVarCall = enableLoginValidateBeforeCall(enableLoginRequest, null);
        Type localVarReturnType = new TypeToken<LogoutDefaultResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Flag a login as enabled.  If a login has been expired due to inactivity, this will enable it to be logged into again (asynchronously)
     * Flag a login as enabled.  If a login has been expired due to inactivity, this will enable it to be logged into again
     * @param enableLoginRequest Flag a login as enabled.  If a login has been expired due to inactivity, this will enable it to be logged into again (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call enableLoginAsync(EnableLoginRequest enableLoginRequest, final ApiCallback<LogoutDefaultResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = enableLoginValidateBeforeCall(enableLoginRequest, _callback);
        Type localVarReturnType = new TypeToken<LogoutDefaultResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getCurrentLogin
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCurrentLoginCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/GetCurrentLogin";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "TokenAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCurrentLoginValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getCurrentLoginCall(_callback);

    }

    /**
     * Returns back info on the current login
     * Returns back info on the current login
     * @return GetCurrentLoginDefaultResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public GetCurrentLoginDefaultResponse getCurrentLogin() throws ApiException {
        ApiResponse<GetCurrentLoginDefaultResponse> localVarResp = getCurrentLoginWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Returns back info on the current login
     * Returns back info on the current login
     * @return ApiResponse&lt;GetCurrentLoginDefaultResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetCurrentLoginDefaultResponse> getCurrentLoginWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getCurrentLoginValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<GetCurrentLoginDefaultResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Returns back info on the current login (asynchronously)
     * Returns back info on the current login
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCurrentLoginAsync(final ApiCallback<GetCurrentLoginDefaultResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCurrentLoginValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<GetCurrentLoginDefaultResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getLogin
     * @param getLoginRequest Return back info on a single login (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLoginCall(GetLoginRequest getLoginRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = getLoginRequest;

        // create path and map variables
        String localVarPath = "/GetLogin";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "TokenAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getLoginValidateBeforeCall(GetLoginRequest getLoginRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'getLoginRequest' is set
        if (getLoginRequest == null) {
            throw new ApiException("Missing the required parameter 'getLoginRequest' when calling getLogin(Async)");
        }

        return getLoginCall(getLoginRequest, _callback);

    }

    /**
     * Return back info on a single login
     * Return back info on a single login
     * @param getLoginRequest Return back info on a single login (required)
     * @return GetCurrentLoginDefaultResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public GetCurrentLoginDefaultResponse getLogin(GetLoginRequest getLoginRequest) throws ApiException {
        ApiResponse<GetCurrentLoginDefaultResponse> localVarResp = getLoginWithHttpInfo(getLoginRequest);
        return localVarResp.getData();
    }

    /**
     * Return back info on a single login
     * Return back info on a single login
     * @param getLoginRequest Return back info on a single login (required)
     * @return ApiResponse&lt;GetCurrentLoginDefaultResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetCurrentLoginDefaultResponse> getLoginWithHttpInfo(GetLoginRequest getLoginRequest) throws ApiException {
        okhttp3.Call localVarCall = getLoginValidateBeforeCall(getLoginRequest, null);
        Type localVarReturnType = new TypeToken<GetCurrentLoginDefaultResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return back info on a single login (asynchronously)
     * Return back info on a single login
     * @param getLoginRequest Return back info on a single login (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLoginAsync(GetLoginRequest getLoginRequest, final ApiCallback<GetCurrentLoginDefaultResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getLoginValidateBeforeCall(getLoginRequest, _callback);
        Type localVarReturnType = new TypeToken<GetCurrentLoginDefaultResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getLogins
     * @param getLoginsRequest Query the login list by setting values, optionally including or excluding logins.  If you leave the settings value empty, you can query just by login id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLoginsCall(GetLoginsRequest getLoginsRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = getLoginsRequest;

        // create path and map variables
        String localVarPath = "/GetLogins";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "TokenAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getLoginsValidateBeforeCall(GetLoginsRequest getLoginsRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'getLoginsRequest' is set
        if (getLoginsRequest == null) {
            throw new ApiException("Missing the required parameter 'getLoginsRequest' when calling getLogins(Async)");
        }

        return getLoginsCall(getLoginsRequest, _callback);

    }

    /**
     * Query the login list by setting values, optionally including or excluding logins.  If you leave the settings value empty, you can query just by login id
     * Query the login list by setting values, optionally including or excluding logins.  If you leave the settings value empty, you can query just by login id
     * @param getLoginsRequest Query the login list by setting values, optionally including or excluding logins.  If you leave the settings value empty, you can query just by login id (required)
     * @return GetLoginsDefaultResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public GetLoginsDefaultResponse getLogins(GetLoginsRequest getLoginsRequest) throws ApiException {
        ApiResponse<GetLoginsDefaultResponse> localVarResp = getLoginsWithHttpInfo(getLoginsRequest);
        return localVarResp.getData();
    }

    /**
     * Query the login list by setting values, optionally including or excluding logins.  If you leave the settings value empty, you can query just by login id
     * Query the login list by setting values, optionally including or excluding logins.  If you leave the settings value empty, you can query just by login id
     * @param getLoginsRequest Query the login list by setting values, optionally including or excluding logins.  If you leave the settings value empty, you can query just by login id (required)
     * @return ApiResponse&lt;GetLoginsDefaultResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetLoginsDefaultResponse> getLoginsWithHttpInfo(GetLoginsRequest getLoginsRequest) throws ApiException {
        okhttp3.Call localVarCall = getLoginsValidateBeforeCall(getLoginsRequest, null);
        Type localVarReturnType = new TypeToken<GetLoginsDefaultResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Query the login list by setting values, optionally including or excluding logins.  If you leave the settings value empty, you can query just by login id (asynchronously)
     * Query the login list by setting values, optionally including or excluding logins.  If you leave the settings value empty, you can query just by login id
     * @param getLoginsRequest Query the login list by setting values, optionally including or excluding logins.  If you leave the settings value empty, you can query just by login id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLoginsAsync(GetLoginsRequest getLoginsRequest, final ApiCallback<GetLoginsDefaultResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getLoginsValidateBeforeCall(getLoginsRequest, _callback);
        Type localVarReturnType = new TypeToken<GetLoginsDefaultResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for renameLogin
     * @param renameLoginRequest Renames a login (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call renameLoginCall(RenameLoginRequest renameLoginRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = renameLoginRequest;

        // create path and map variables
        String localVarPath = "/RenameLogin";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "TokenAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call renameLoginValidateBeforeCall(RenameLoginRequest renameLoginRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'renameLoginRequest' is set
        if (renameLoginRequest == null) {
            throw new ApiException("Missing the required parameter 'renameLoginRequest' when calling renameLogin(Async)");
        }

        return renameLoginCall(renameLoginRequest, _callback);

    }

    /**
     * Renames a login
     * Renames a login
     * @param renameLoginRequest Renames a login (required)
     * @return LogoutDefaultResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public LogoutDefaultResponse renameLogin(RenameLoginRequest renameLoginRequest) throws ApiException {
        ApiResponse<LogoutDefaultResponse> localVarResp = renameLoginWithHttpInfo(renameLoginRequest);
        return localVarResp.getData();
    }

    /**
     * Renames a login
     * Renames a login
     * @param renameLoginRequest Renames a login (required)
     * @return ApiResponse&lt;LogoutDefaultResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LogoutDefaultResponse> renameLoginWithHttpInfo(RenameLoginRequest renameLoginRequest) throws ApiException {
        okhttp3.Call localVarCall = renameLoginValidateBeforeCall(renameLoginRequest, null);
        Type localVarReturnType = new TypeToken<LogoutDefaultResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Renames a login (asynchronously)
     * Renames a login
     * @param renameLoginRequest Renames a login (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call renameLoginAsync(RenameLoginRequest renameLoginRequest, final ApiCallback<LogoutDefaultResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = renameLoginValidateBeforeCall(renameLoginRequest, _callback);
        Type localVarReturnType = new TypeToken<LogoutDefaultResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateLogin
     * @param addLoginRequest Update a login (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateLoginCall(AddLoginRequest addLoginRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = addLoginRequest;

        // create path and map variables
        String localVarPath = "/UpdateLogin";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "TokenAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateLoginValidateBeforeCall(AddLoginRequest addLoginRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'addLoginRequest' is set
        if (addLoginRequest == null) {
            throw new ApiException("Missing the required parameter 'addLoginRequest' when calling updateLogin(Async)");
        }

        return updateLoginCall(addLoginRequest, _callback);

    }

    /**
     * Update a login
     * Update a login
     * @param addLoginRequest Update a login (required)
     * @return LogoutDefaultResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public LogoutDefaultResponse updateLogin(AddLoginRequest addLoginRequest) throws ApiException {
        ApiResponse<LogoutDefaultResponse> localVarResp = updateLoginWithHttpInfo(addLoginRequest);
        return localVarResp.getData();
    }

    /**
     * Update a login
     * Update a login
     * @param addLoginRequest Update a login (required)
     * @return ApiResponse&lt;LogoutDefaultResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LogoutDefaultResponse> updateLoginWithHttpInfo(AddLoginRequest addLoginRequest) throws ApiException {
        okhttp3.Call localVarCall = updateLoginValidateBeforeCall(addLoginRequest, null);
        Type localVarReturnType = new TypeToken<LogoutDefaultResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a login (asynchronously)
     * Update a login
     * @param addLoginRequest Update a login (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateLoginAsync(AddLoginRequest addLoginRequest, final ApiCallback<LogoutDefaultResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateLoginValidateBeforeCall(addLoginRequest, _callback);
        Type localVarReturnType = new TypeToken<LogoutDefaultResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateLoginEx
     * @param updateLoginExRequest Updates pieces of a login (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateLoginExCall(UpdateLoginExRequest updateLoginExRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateLoginExRequest;

        // create path and map variables
        String localVarPath = "/UpdateLoginEx";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "TokenAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateLoginExValidateBeforeCall(UpdateLoginExRequest updateLoginExRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'updateLoginExRequest' is set
        if (updateLoginExRequest == null) {
            throw new ApiException("Missing the required parameter 'updateLoginExRequest' when calling updateLoginEx(Async)");
        }

        return updateLoginExCall(updateLoginExRequest, _callback);

    }

    /**
     * Updates pieces of a login
     * Updates pieces of a login
     * @param updateLoginExRequest Updates pieces of a login (required)
     * @return LogoutDefaultResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public LogoutDefaultResponse updateLoginEx(UpdateLoginExRequest updateLoginExRequest) throws ApiException {
        ApiResponse<LogoutDefaultResponse> localVarResp = updateLoginExWithHttpInfo(updateLoginExRequest);
        return localVarResp.getData();
    }

    /**
     * Updates pieces of a login
     * Updates pieces of a login
     * @param updateLoginExRequest Updates pieces of a login (required)
     * @return ApiResponse&lt;LogoutDefaultResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LogoutDefaultResponse> updateLoginExWithHttpInfo(UpdateLoginExRequest updateLoginExRequest) throws ApiException {
        okhttp3.Call localVarCall = updateLoginExValidateBeforeCall(updateLoginExRequest, null);
        Type localVarReturnType = new TypeToken<LogoutDefaultResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Updates pieces of a login (asynchronously)
     * Updates pieces of a login
     * @param updateLoginExRequest Updates pieces of a login (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateLoginExAsync(UpdateLoginExRequest updateLoginExRequest, final ApiCallback<LogoutDefaultResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateLoginExValidateBeforeCall(updateLoginExRequest, _callback);
        Type localVarReturnType = new TypeToken<LogoutDefaultResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
